name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Etapa de Instalação de dependências e compilação
    - name: Install dependencies and build
      run: |
        cp .env.example .env
        sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env
        sed -i "s/APP_NAME=.*/APP_NAME=QuizGameBackend/g" .env
        sed -i "s/DB_HOST=.*/DB_HOST=54.233.149.212/g" .env
        sed -i "s/DB_PORT=.*/DB_PORT=5432/g" .env
        sed -i "s/DB_DATABASE=.*/DB_DATABASE=postgres/g" .env
        sed -i "s/DB_USERNAME=.*/DB_USERNAME=postgres/g" .env
        sed -i "s/DB_SCHEMA=.*/DB_SCHEMA=public/g" .env  
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/g" .env
        docker-compose build
    # Etapa de Deploy na máquina de produção
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: 54.233.149.212
        username: tauan
        password: 8617775759
        script: |
          cp .env.example .env
          sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env
          sed -i "s/APP_NAME=.*/APP_NAME=QuizGameBackend/g" .env
          sed -i "s/DB_HOST=.*/DB_HOST=54.233.149.212/g" .env
          sed -i "s/DB_PORT=.*/DB_PORT=5432/g" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=postgres/g" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=postgres/g" .env
          sed -i "s/DB_SCHEMA=.*/DB_SCHEMA=public/g" .env  
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/g" .env
          docker-compose up -d
          docker-compose exec app bash -c "php artisan key:generate && php artisan migrate"
