name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#     # Etapa de Instalação de dependências e compilação
#     - name: Install dependencies and build
#       run: |
#         composer install
#         cp .env.example .env
#         sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env
#         sed -i "s/APP_NAME=.*/APP_NAME=QuizGameBackend/g" .env
#         sed -i "s/DB_HOST=.*/DB_HOST=54.232.152.192/g" .env
#         sed -i "s/DB_PORT=.*/DB_PORT=5432/g" .env
#         sed -i "s/DB_DATABASE=.*/DB_DATABASE=postgres/g" .env
#         sed -i "s/DB_USERNAME=.*/DB_USERNAME=postgres/g" .env
#         sed -i "s/DB_SCHEMA=.*/DB_SCHEMA=public/g" .env  
#         sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/g" .env
#         docker-compose up -d
#         docker-compose exec app bash -c "php artisan key:generate && php artisan migrate"

    # Etapa de Deploy na máquina de produção
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: 54.232.152.192
        username: ubuntu
        key: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEArxIh5deKKBwblJhMw7HxovZpNgYFxI6ds7HKq1h/AKRezn61HvvIgq5OTu2Qou1jLVOMvyGgOPY5LoMMZ6AMO5RZNClZq9j16188r5drnwHZYukSPqf9UgiqVsc8kng116Sg/iewdm3CsLNFKYYLqPBklaGQLHVe+ixxUmWbbnL/Qdv7vnLEaamA9rdr4oT10OXLk3VJyhVEVWs5kYNF0ZYQqB0T33Mfrhez7mGK0Tb0h5XIWBeoxMaTdbfg8S58uf+C0zoWXnmA7SGhrx0QqTEmHmmp2BiHuOr4ARPFNVuINpjopKPYDiCMZt3e3F+LasrMu8cWMurnogDhDnBrwIDAQABAoIBAA4Ay0lRFjHjHamjDPDSONuqDfxOOwPfzGllHSrbZz0r6JFnvSD/Tqh1PLo/ckQ17Krhde6Lx/8GYsh/nuxi9teFJCVx8UQ3lGQBOB9rYZSxYqNzfHJChAXtVg/k267wsK+3km17v1qBhqQHEYX/LLEl6cIRznnIXOtPlsy2V3aHmpKVo9aPBPII+RmR0GZki1slcuTAk4JtOQvETTE0L+aXaXAMNaf9sLwoAdwmrWAszfeIsO4Lp3dTN/bChlZf7H8SZ/+bsXXquuW2L1lyQpMaTEn8yr0fiJ6FS1MFZDLb4gYxHYq3KfOK4kEvqNqpqutWDAt1PRyAN1Cm1kdJxECgYEA/+2IXqVOkLU4AGtRPIc5pOk09AzcGJ4WxbtCMIgOxETChJfA/2YDNpZTE+RcJsFvqrocm3U/SiYe7VSsfVybSLz6CRh9OHrNsGf0LJ3Uq+muTwY/Hop2s07O/Q9KjWNtANZc6/XhZGdO5CqmVlwW29Yq9pC7jS918OBypiCPGXUCgYEArx7D5Uscan+Xg0DE2LoYDHxPshv/jxTxXGwPkpFqFCLlES+fcU1NZKL6j0V93wXDzDYxch2FHJW+W7n/X0Wt5qaSpJWYOFyWxkOtaEbZsEKIdUyjFwzv9X/wjsaBWSNwIAnVSf1vD19MzUIf5gGXyEm4GT6CCxYU9yOMaVphMCgYEAg7v6w+0HIcmGCAE1kZhxfYdk8HJmIG3PfvxCt8RxBWn3TlTmzQ/ve3upS8XyASj0l8awzvxtFXfF15gMKYMvkyNi+KeYXSgpFDKOJyEexVbFmHu4pbnUG7vnI69pSpnxE8tDjVnFKO9cVmn1sOI6CfKVrtEVGTli1hhSK1z7C7kCgYAdRyp/UnB8ybo+In0Gsw5EQCBe6dlvRZQY3KQ53//5P+BGYEzq936h/bGyVrYue1kLrcI7xwke4AL0jvtQYTKEHd//6blxVx/0ZRsVeMsJAes8vtVFrECmqROqmJEAJ9CfR43L6fNmtm0RO6OhGXyvOO60A43eAfP+iVhoqnwawKBgDBJrMa/V/dv7BZU+JuVA03PhrQPUpN3d98BCpJ1ZhTu/LrvCsum5OE2EclAxfI4qrCWR5wcSlPJWKkUtcpAXdRQ0ichwP4v7G2TJKnb58PT++6jgve4rseUveJRMC1m2LUxWEDvmYKOqRLwpc0vnJt01SCEluVlFgX0r1HNtkfc-----END RSA PRIVATE KEY-----"
        script: |
          ls -la
          pwd
          cd /path
          
