name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Etapas para atualizar a aplicação na máquina de produção
    - name: Update application on production server
      run: |
        ssh -i ~/.ssh/id_rsa user@production-server 'cd /path/to/application && git pull origin main && chmod -R 777 ./ && composer install && cp .env.example .env && sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env && sed -i "s/APP_NAME=.*/APP_NAME=QuizGameBackend/g" .env && sed -i "s/DB_HOST=.*/DB_HOST=54.232.152.192/g" .env && sed -i "s/DB_PORT=.*/DB_PORT=5432/g" .env && sed -i "s/DB_DATABASE=.*/DB_DATABASE=postgres/g" .env && sed -i "s/DB_USERNAME=.*/DB_USERNAME=postgres/g" .env && sed -i "s/DB_SCHEMA=.*/DB_SCHEMA=public/g" .env  && sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/g" .env && docker-compose up -d && docker-compose exec app bash -c "php artisan key:generate && php artisan migrate "'
