name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Etapa de Instalação de dependências e compilação
    - name: Install dependencies and build
      run: |
        composer install
        cp .env.example .env 2>/dev/null
        echo $KEY
        sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env
        sed -i "s/APP_NAME=.*/APP_NAME=QuizGameBackend/g" .env
        sed -i "s/DB_HOST=.*/DB_HOST=54.232.152.192/g" .env
        sed -i "s/DB_PORT=.*/DB_PORT=5432/g" .env
        sed -i "s/DB_DATABASE=.*/DB_DATABASE=postgres/g" .env
        sed -i "s/DB_USERNAME=.*/DB_USERNAME=postgres/g" .env
        sed -i "s/DB_SCHEMA=.*/DB_SCHEMA=public/g" .env  
        sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/g" .env
        docker-compose up -d
        docker-compose exec app bash -c "php artisan key:generate && php artisan migrate"

    # Etapa de Deploy na máquina de produção
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        script: |
          ssh -i $KEY -o StrictHostKeyChecking=no ubuntu@ec2-54-232-152-192.sa-east-1.compute.amazonaws.com "ls -la"
          
